from django.urls import path
from .views import *


urlpatterns = [
    path('', home),
    path('api/example', example_view),
    path('api/submit', create_user),
    path('api/login', login),
    path('api/retrieve', retrieve_user),
    path('api/retrieve_member', retrieve_member),
    path('api/profile', retrieve_specific_user),
    path('api/change_pass', change_pass),
    path('api/update_profile', update_profile),
    path('api/delete_account', delete_acc),
    path('api/tasks', retrieve_tasks),
    path('api/projects', retrieve_project),
    path('api/create_project', create_project),
    path('api/members', retrieve_members),
    path('api/create_member', create_members),
    path('api/new_task', create_task),
    path('api/rm_task', delete_task),
    path('api/rm_member', delete_member),
    path('api/retrieve_member_project', retrieve_member_project),
    path('api/member_task', get_specific_task),
    path('api/update_task', update_task),
    path('api/indiv_task', get_member_task),
    path('api/update_indiv_task', update_indiv_task),
    path('api/add_member',add_members),
    path('api/retrieve_all_mem', retrieve_all_members),
    path('api/retrieve_mem_proj', get_mem_proj),
    path('api/del_member', del_memss),
    path('api/update_description', update_project_description),
    path('api/update_date_gant', update_task_date_gant),
    path('api/retrieve_project_description', retrieve_project_description),
    path('api/notifications/<str:username>/', get_notifications, name='get_notifications'),
]
