# Generated by Django 5.1.3 on 2024-12-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('assigned', models.CharField(max_length=255)),
                ('sprint', models.IntegerField()),
                ('priority', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
    ]
