# Generated by Django 5.1.3 on 2024-12-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('project_manager', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
    ]
