# Generated by Django 5.1.3 on 2024-12-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_Project',
            fields=[
                ('assigned_project_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'assigned_projects',
                'managed': False,
            },
        ),
    ]
