# Generated by Django 5.1.3 on 2024-12-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proj',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'managed': False},
        ),
    ]
