# Generated by Django 5.1.3 on 2024-12-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_assigned_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Project',
            fields=[
                ('assigned_project_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'member_projects',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Assigned_Project',
        ),
    ]
